# This is converter generated file, and shall not be touched by user
#
# It is always re-generated if converter script is called multiple times
# Use CMakeLists.txt to apply user changes
cmake_minimum_required(VERSION 3.22)

# Core MCU flags, CPU, instruction set and FPU setup
set(cpu_PARAMS ${cpu_PARAMS}
    -mthumb

    # Other parameters
    # -mcpu, -mfloat, -mfloat-abi, ...
    -mcpu=cortex-m4
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
)

# Linker script
set(linker_script_SRC ${linker_script_SRC}
    ${CMAKE_CURRENT_SOURCE_DIR}/STM32F407ZGTX_FLASH.ld
)

# Sources
set(sources_SRCS ${sources_SRCS}
    ${CMAKE_CURRENT_SOURCE_DIR}/AZURE_RTOS/App/app_azure_rtos.c
    ${CMAKE_CURRENT_SOURCE_DIR}/USBX/App/app_usbx_host.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Lib/uart_idle_rx/uart_comm_helper.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/app_threadx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/dma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/fsmc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/gpio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/main.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/stm32f4xx_hal_msp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/stm32f4xx_hal_timebase_tim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/stm32f4xx_it.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/syscalls.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/sysmem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/system_stm32f4xx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/usart.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/usb_otg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/tx_initialize_low_level.s
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Startup/startup_stm32f407zgtx.s
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_block_allocate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_block_pool_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_block_pool_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_block_pool_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_block_pool_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_block_release.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_byte_allocate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_byte_pool_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_byte_pool_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_byte_pool_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_byte_pool_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_byte_release.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_event_flags_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_event_flags_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_event_flags_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_event_flags_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_event_flags_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_event_flags_set_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_mutex_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_mutex_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_mutex_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_mutex_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_mutex_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_mutex_put.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_queue_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_queue_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_queue_flush.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_queue_front_send.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_queue_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_queue_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_queue_receive.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_queue_send.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_queue_send_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_semaphore_ceiling_put.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_semaphore_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_semaphore_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_semaphore_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_semaphore_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_semaphore_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_semaphore_put.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_semaphore_put_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_entry_exit_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_preemption_change.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_priority_change.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_relinquish.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_reset.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_resume.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_suspend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_terminate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_time_slice_change.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_thread_wait_abort.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_timer_activate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_timer_change.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_timer_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_timer_deactivate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_timer_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/txe_timer_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_allocate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_pool_cleanup.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_pool_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_pool_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_pool_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_pool_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_pool_performance_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_pool_performance_system_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_pool_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_block_release.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_allocate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_pool_cleanup.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_pool_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_pool_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_pool_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_pool_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_pool_performance_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_pool_performance_system_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_pool_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_pool_search.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_byte_release.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_cleanup.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_performance_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_performance_system_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_event_flags_set_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_initialize_high_level.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_initialize_kernel_enter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_initialize_kernel_setup.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_cleanup.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_performance_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_performance_system_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_priority_change.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_mutex_put.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_cleanup.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_flush.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_front_send.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_performance_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_performance_system_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_receive.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_send.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_queue_send_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_ceiling_put.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_cleanup.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_performance_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_performance_system_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_prioritize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_put.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_semaphore_put_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_entry_exit_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_identify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_performance_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_performance_system_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_preemption_change.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_priority_change.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_relinquish.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_reset.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_resume.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_shell_entry.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_sleep.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_stack_analyze.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_stack_error_handler.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_stack_error_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_suspend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_system_preempt_check.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_system_resume.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_system_suspend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_terminate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_timeout.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_time_slice.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_time_slice_change.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_thread_wait_abort.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_activate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_change.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_deactivate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_expiration_process.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_performance_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_performance_system_info_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_system_activate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_system_deactivate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_timer_thread_entry.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_time_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_time_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_buffer_full_notify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_disable.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_enable.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_event_filter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_event_unfilter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_interrupt_control.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_isr_enter_insert.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_isr_exit_insert.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_object_register.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_object_unregister.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/src/tx_trace_user_event_insert.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/utility/low_power/tx_low_power.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_bandwidth_check.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_bandwidth_claim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_bandwidth_release.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_call.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_device_scan.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_instance_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_instance_destroy.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_instance_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_instance_verify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_interface_scan.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_register.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_class_unregister.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_descriptor_parse.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_enumerate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_instance_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_instance_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_interface_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_interface_scan.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_configuration_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_delay_ms.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_address_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_activate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_deactivate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_reset.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_configuration_select.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_descriptor_read.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_remove.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_resources_free.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_device_string_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_endpoint_instance_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_endpoint_instance_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_endpoint_reset.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_endpoint_transfer_abort.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_enum_thread_entry.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_hcd_register.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_hcd_thread_entry.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_hcd_transfer_request.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_hcd_unregister.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_hnp_polling_thread_entry.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_interfaces_scan.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_endpoint_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_instance_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_instance_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_interface_setting_select.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_new_configuration_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_new_device_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_new_device_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_new_endpoint_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_new_interface_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_rh_change_process.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_rh_device_extraction.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_rh_device_insertion.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_role_swap.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_transfer_request.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_transfer_request_abort.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_host_stack_uninitialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_system_error_handler.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_system_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_system_uninitialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_debug_callback_register.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_debug_log.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_delay_ms.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_descriptor_pack.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_descriptor_parse.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_error_callback_register.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_event_flags_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_event_flags_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_event_flags_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_event_flags_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_long_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_long_get_big_endian.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_long_put.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_long_put_big_endian.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate_add_safe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate_mulc_safe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate_mulv_safe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_memory_compare.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_memory_copy.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_memory_free.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_memory_free_block_best_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_memory_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_mutex_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_mutex_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_mutex_off.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_mutex_on.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_pci_class_scan.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_pci_read.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_pci_write.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_physical_address.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_semaphore_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_semaphore_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_semaphore_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_semaphore_put.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_set_interrupt_handler.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_short_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_short_get_big_endian.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_short_put.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_short_put_big_endian.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_string_length_check.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_string_length_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_string_to_unicode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_thread_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_thread_delete.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_thread_identify.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_thread_relinquish.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_thread_resume.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_thread_schedule_other.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_thread_sleep.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_thread_suspend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_timer_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_unicode_to_string.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/src/ux_utility_virtual_address.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_activate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_alternate_setting_locate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_channel_start.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_configure.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_control_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_control_list_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_control_request.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_control_value_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_control_value_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_deactivate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_descriptor_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_endpoints_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_entities_parse.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_entry.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_format_data_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_frame_data_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_frame_interval_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_frame_parameters_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_input_format_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_input_terminal_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_ioctl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_max_payload_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_read.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_start.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_stop.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_transfer_buffers_add.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_transfer_buffer_add.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_transfer_callback_set.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_transfer_request.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_transfer_request_callback.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/src/ux_host_class_video_transfer_request_completed.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_callback.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_controller_disable.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_ed_obtain.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_endpoint_create.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_endpoint_destroy.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_endpoint_reset.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_entry.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_frame_number_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_initialize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_interrupt_handler.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_least_traffic_list_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_periodic_schedule.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_disable.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_enable.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_reset.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_resume.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_status_get.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_port_suspend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_power_down_port.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_power_on_port.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_bulk_transfer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_control_transfer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_periodic_transfer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_request_transfer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers/ux_hcd_stm32_transfer_abort.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_context_restore.S
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_context_save.S
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_interrupt_control.S
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_schedule.S
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_stack_build.S
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_thread_system_return.S
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/ports/cortex_m4/gnu/src/tx_timer_interrupt.S
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
)

# Include directories
set(include_c_DIRS ${include_c_DIRS}
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}Core/Lib
    ${CMAKE_CURRENT_SOURCE_DIR}Core/Lib/uart_idle_rx
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/CMSIS/Device/ST/STM32F4xx/Include
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/CMSIS/Include
    ${CMAKE_CURRENT_SOURCE_DIR}/AZURE_RTOS/App
    ${CMAKE_CURRENT_SOURCE_DIR}/USBX/App
    ${CMAKE_CURRENT_SOURCE_DIR}/USBX/Target
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_host_classes/inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/core/inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/ports/generic/inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/common/inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/ports/cortex_m4/gnu/inc
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/threadx/utility/low_power
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/usbx/common/usbx_stm32_host_controllers
)
set(include_cxx_DIRS ${include_cxx_DIRS}
    
)
set(include_asm_DIRS ${include_asm_DIRS}
    
)

# Symbols definition
set(symbols_c_SYMB ${symbols_c_SYMB}
    "DEBUG"
    "USE_HAL_DRIVER"
    "STM32F407xx"
    "TX_INCLUDE_USER_DEFINE_FILE"
    "UX_INCLUDE_USER_DEFINE_FILE"
)
set(symbols_cxx_SYMB ${symbols_cxx_SYMB}
    
)
set(symbols_asm_SYMB ${symbols_asm_SYMB}
    "DEBUG"
)

# Link directories
set(link_DIRS ${link_DIRS}
    
)

# Link libraries
set(link_LIBS ${link_LIBS}
    
)

# Compiler options
set(compiler_OPTS ${compiler_OPTS})

# Linker options
set(linker_OPTS ${linker_OPTS})
